added support for CURL on Linux
git-svn-id: https://codelite.svn.sourceforge.net/svnroot/codelite/trunk@1639 9da81c78-c036-0410-9e1f-a2b0375e4b5a

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -389,7 +389,18 @@ createEndMessage()
 	fi
 }
 
+checkCURL()
+{
+	if [ -d "/usr/include/curl/" ] || [ -d "/usr/local/include/curl/" ] ; then
+		echo "Found cURL installation"
+	else
+		echo "ERROR: Please install libcurl development package (under Ubuntu 7.10, the package name is libcurl4-dev)"
+		exit 1
+	fi
+}
+
 ## main
+checkCURL
 
 ## Create variables needed by the makefile
 enable_debug="no"
